"""Directory names every repository walker skips."""

EXCLUDED_DIRS = {
    ".git",
    "node_modules",
    "vendor",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".tox",
    ".venv",
    "venv",
    "env",
    ".env",
    "dist",
    "build",
    "out",
    "target",
    "bin",
    "obj",
    ".idea",
    ".vscode",
    ".claude",
    ".cursor",
    ".agent_workspace",
    "coverage",
    ".nyc_output",
    ".next",
    ".nuxt",
    ".cache",
    "tmp",
    "temp",
    ".ruff_cache",
    ".vale",
    ".work",
    ".docs-gen",
}
